### ISSUE TITLE
Getting error whith this skill

### ISSUE THREAD

**Issue by andlo** [snipsco/snips-skill-owm#3]
It loads fine, but when running snipsmanager run Ill see this
...
2017-11-18 22:25:45 [INFO] Loading skill snipsowm
2017-11-18 22:25:45 [ERROR] Error loading skill snipsowm: __init__() takes at least 3 arguments (1 given)
...

Cant figure out what I am missing

**Comment by ashwinvandijk** [comment]
I got the same error, although it's a little bit different:

```
snipsmanager run
[INFO] Starting Snips Manager
[INFO] Loading skill snipsowm
[ERROR] Error loading skill snipsowm: __init__() takes at least 3 arguments (1 given)
```

**Comment by andlo** [comment]
At the moment I cant reproduse the problem....I did a reinstall og raspbian and snips, and dont see the same error. But I sill dosnt have any output voise - only blim and blam sound. And cant figure out what I am missing.

**Comment by psychonetic** [comment]
I got another error. When starting with snipsmanager I got the following error:
 `Error loading skill snipsowm: __init__() got an unexpected keyword argument 'locale'`

**Comment by noli2000** [comment]
@psychonetic, The version of snipsowm currently installed py pip is not the latest version and does contain the code modifications done recently on this repo.

**Comment by dest4** [comment]
In the Snipsfile, I tried replacing `pip: snipsown` by `pip: git+https://github.com/snipsco/snips-skill-owm.git`. I could install the skill, but I get another error when doing `snipsmanger run`: `Error loading skill snipsowm: No module named enum`.
I am confused as `sudo pip install enum34` gives `Requirement already satisfied: enum34 in /usr/local/lib/python3.4/dist-packages`. Any clue?

**Comment by yxdunc** [comment]
Hello everyone, the last update of snips-skill-owm along with the latest version of snipsmanager should solve all your issues.

**Comment by dest4** [comment]
On my setup, now it's still missing an argument (different than earlier reports, where two were missing).
I would appreciate to know what I am doing wrong here.

```
$ snipsmanager run
2017-12-29 16:19:10 [INFO] Starting Snips Manager
2017-12-29 16:19:10 [INFO] Loading skill snipsowm
2017-12-29 16:19:10 [ERROR] Error loading skill snipsowm: __init__() takes at least 3 arguments (2 given)
```
Some debug info:
```
$ sudo apt-get update && sudo apt-get dist-upgrade
Hit https://raspbian.snips.ai stable InRelease                                                                       
(...)
Hit https://raspbian.snips.ai stable/main armhf Packages                     
(...)                             
Get:4 https://raspbian.snips.ai stable/main Translation-en
Get:5 https://raspbian.snips.ai stable/main Translation-en_GB
Get:6 https://raspbian.snips.ai stable/main Translation-en
Get:7 https://raspbian.snips.ai stable/main Translation-en_GB
Get:8 https://raspbian.snips.ai stable/main Translation-en
Get:9 https://raspbian.snips.ai stable/main Translation-en_GB
Ign https://raspbian.snips.ai stable/main Translation-en_GB
Get:10 https://raspbian.snips.ai stable/main Translation-en
Ign https://raspbian.snips.ai stable/main Translation-en                                                               
(...)
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
```
$ snipsmanager --version
0.1.6.42
```
```
(snipsmanager) pi@rpivoice:~ $ pip install git+https://github.com/snipsco/snips-skill-owm.git
Collecting git+https://github.com/snipsco/snips-skill-owm.git
  Cloning https://github.com/snipsco/snips-skill-owm.git to /tmp/pip-DL5K7G-build
Requirement already satisfied: requests==2.6.0 in /opt/venvs/snipsmanager/lib/python2.7/site-packages (from snipsowm==0.1.3)
Requirement already satisfied: enum34==1.1.6 in /opt/venvs/snipsmanager/lib/python2.7/site-packages (from snipsowm==0.1.3)
Requirement already satisfied: python-Levenshtein in /opt/venvs/snipsmanager/lib/python2.7/site-packages (from snipsowm==0.1.3)
Requirement already satisfied: setuptools in /opt/venvs/snipsmanager/lib/python2.7/site-packages (from python-Levenshtein->snipsowm==0.1.3)
Installing collected packages: snipsowm
  Running setup.py install for snipsowm ... done
Successfully installed snipsowm-0.1.3
```
```
$ cat Snipsfile
assistant_file: assistant_proj_41PGpgEObve_weather.zip
default_location: Paris,fr
skills:
- package_name: snipsowm
  class_name: SnipsOWM
  pip: git+https://github.com/snipsco/snips-skill-owm.git
  default_location: "Paris,fr"
  api_key: 12A4F912EA29100B2C
  intents:
    - intent: GetWeather
      action: "get_weather"
```
```
$ sudo snipsmanager install
Running Snips Manager installer
❯ Fetching assistant
✔ Copying assistant assistant_proj_41PGpgEObve_weather.zip to /home/pi/.snips/assistant.zip
❯ Loading assistant
✔ Loading assistant from file /home/pi/.snips/assistant.zip
✔ Generating classes from assistant model
✔ Assistant has been successfully loaded
❯ Installing skills
✔ Installing skill: git+https://github.com/snipsco/snips-skill-owm.git
✔ Successfully installed 1 skill
❯ Setting up microphone
✔ Copying asound configuration to /etc/asound.conf
✔ Microphone setup successfully complete
❯ Setting up speaker
✔ Installing driver
✔ Copying asound.conf to /etc/asound.conf
✔ Speaker setup successfully complete
❯ Setting up Bluetooth
✔ Bluetooth is successfully installed
❯ Setting up Bluetooth as a Systemd service
✔ Successfully set up Bluetooth as a Systemd service
❯ Setting up Snips Manager as a Systemd service
✔ Successfully set up Snips Manager as a Systemd service
Snips Manager installer complete! You can now reboot your device, or manually run 'snipsmanager run' to start the Snips Manager server
```
```
$ cat /etc/debian_version 
8.0
```

**Comment by yxdunc** [comment]
HEllo,
It's probably caused by the Snipsfile which should have `default_location` and `api_key` in the section `params:`
```
- package_name: snipsowm
  class_name: SnipsOWM
  params:
    default_location: "Paris,fr"
    api_key: 12A4F912EA29100B2C
```

**Comment by dest4** [comment]
OK now it starts. Hurray & thanks!
You should probably edit the documentation to reflect this.
Now it crashes when I ask for weather... `AttributeError: SearchWeatherForecastIntent instance has no attribute 'forecast_start_datetime'`


```
$ snipsmanager run
2017-12-29 16:50:28 [INFO] New message on topic hermes/hotword/default/detected
2017-12-29 16:50:28 [INFO] New message on topic hermes/asr/stopListening
2017-12-29 16:50:28 [INFO] New message on topic hermes/hotword/toggleOff
2017-12-29 16:50:28 [INFO] New message on topic hermes/dialogueManager/sessionStarted
2017-12-29 16:50:28 [INFO] New message on topic hermes/asr/startListening
2017-12-29 16:50:33 [INFO] New message on topic hermes/asr/textCaptured
2017-12-29 16:50:33 [INFO] New message on topic hermes/asr/stopListening
2017-12-29 16:50:33 [INFO] New message on topic hermes/intent/searchWeatherForecast
Exception in thread Thread-40:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/venvs/snipsmanager/local/lib/python2.7/site-packages/snipsmanager/commands/run.py", line 185, in handle_intent
    exec(action, action_scope)
  File "<string>", line 7, in <module>
AttributeError: SearchWeatherForecastIntent instance has no attribute 'forecast_start_datetime'

2017-12-29 16:50:39 [INFO] New message on topic hermes/dialogueManager/sessionEnded
2017-12-29 16:50:39 [INFO] New message on topic hermes/asr/stopListening
2017-12-29 16:50:39 [INFO] New message on topic hermes/hotword/toggleOn
```

```
$ snips-watch -vvv
[16:50:26] Watching on localhost:1883
[16:50:28] [Hotword] detected on site default
[16:50:28] [Asr] was asked to stop listening on site default
[16:50:28] [Hotword] was asked to toggle itself 'off' on site default
[16:50:28] [Dialogue] session with id '5f668667-0b31-491c-952e-e0220de3cc23' was started on site default
[16:50:28] [Asr] was asked to listen on site default
[16:50:33] [Asr] captured text "il fait beau à paris aujourd'hui" in 5.2s
[16:50:33] [Asr] was asked to stop listening on site default
[16:50:33] [Nlu] was asked to parse input il fait beau à paris aujourd'hui
[16:50:33] [Nlu] detected intent searchWeatherForecast with probability 0.838 for input "il fait beau à paris aujourd'hui"
              Slots ->
                        forecast_locality -> Paris
                 forecast_start_date_time -> 2017-12-29 00:00:00 +01:00
[16:50:33] [Dialogue] New intent detected searchWeatherForecast with probability 0.838
              Slots ->
                        forecast_locality -> Paris
                 forecast_start_date_time -> 2017-12-29 00:00:00 +01:00
[16:50:39] [Dialogue] session with id '5f668667-0b31-491c-952e-e0220de3cc23' was ended on site default. The session was ended because one of the component didn't respond in a timely manner
[16:50:39] [Asr] was asked to stop listening on site default
[16:50:39] [Hotword] was asked to toggle itself 'on' on site default
```

**Comment by yxdunc** [comment]
This happened because of the last snipsmanager update... Sorry for the trouble.

Here is a branch of snipsmanager fixing the problem:  https://github.com/snipsco/snipsmanager/tree/extending_snips_object.

**Comment by dest4** [comment]
OK so I downloaded that branch, 
`$ git clone -b extending_snips_object https://github.com/snipsco/snipsmanager.git`
then did
`$ sudo python snipsmanager/setup.py build`
`$ sudo python snipsmanager/setup.py install`
waited a couple minutes, got an error about `error: Setup script exited with error: unknown file type '.pyx' (from 'hid.pyx')`, installed manually a newer version of setuptools, redid the install that got successful.
But my new snipsmanager does not seem operational. Are there building instructions somewhere?

```
$ snipsmanager --version
Traceback (most recent call last):
  File "/usr/local/bin/snipsmanager", line 11, in <module>
    load_entry_point('snipsmanager==0.1.6.41', 'console_scripts', 'snipsmanager')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named snipsmanager.cli
```
